export const ALL_COMMENT = 'ALL_COMMENT'
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'

export const INSERT_COMMENT = 'INSERT_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'