// Project category
export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY'
export const PROJECT_CATEGORY = 'PROJECT_CATEGORY'
// Project
export const POST_CREATE_PROJECT = 'POST_CREATE_PROJECT'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const ALL_PROJECT = 'ALL_PROJECT'

export const DELETE_PROJECT = 'DELETE_PROJECT'

export const EDIT_PROJECT = 'EDIT_PROJECT'
export const EDIT_PROJECT_DRAWER = 'EDIT_PROJECT_DRAWER'
export const ON_SUBMIT_DRAWER = 'ON_SUBMIT_DRAWER'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const CLOSE_DRAWER = 'CLOSE_DRAWER'

export const PROJECT_DETAIL = 'PROJECT_DETAIL'
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'