export const SIGN_UP_USER = 'SIGN_UP_USER'
export const USER_SIGN_IN_API = 'USER_SIGN_IN_API'

export const ALL_USER = 'ALL_USER'
export const GET_ALL_USER = 'GET_ALL_USER'

export const ADD_USER_IN_PROJECT = 'ADD_USER_IN_PROJECT'
export const POST_ADD_USER_IN_PROJECT = 'POST_ADD_USER_IN_PROJECT'

export const DELETE_USER_IN_PROJECT = 'DELETE_USER_IN_PROJECT'
export const POST_DELETE_USER_IN_PROJECT = 'POST_DELETE_USER_IN_PROJECT'

export const USER_BY_PROJECT = 'USER_BY_PROJECT'
export const GET_USER_BY_PROJECT = 'GET_USER_BY_PROJECT'

export const ALL_USER_1 = 'ALL_USER_1'
export const GET_ALL_USER_1 = 'GET_ALL_USER_1'

export const CREATE_USER = 'CREATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'

export const LOG_OUT = 'LOG_OUT'